[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Configuración para el dominio principal (portfolio)
[[redirects]]
  from = "https://jesusvelez.dev/Blog/*"
  to = "https://blog.jesusvelez.dev/Blog/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://jesusvelez.dev/DevBlog"
  to = "https://blog.jesusvelez.dev/DevBlog"
  status = 301
  force = true

# Configuración para el subdominio blog
[[redirects]]
  from = "https://blog.jesusvelez.dev/"
  to = "https://blog.jesusvelez.dev/DevBlog"
  status = 200

# Manejar rutas SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers para CORS si es necesario
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Configuración específica para archivos estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
