[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22.12.0"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "https://jesusvelez.xyz/Blog/*"
  to = "https://blog.jesusvelez.xyz/Blog/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://jesusvelez.xyz/DevBlog"
  to = "https://blog.jesusvelez.xyz/DevBlog"
  status = 301
  force = true

[[redirects]]
  from = "https://blog.jesusvelez.xyz/"
  to = "https://blog.jesusvelez.xyz/DevBlog"
  status = 200

[[redirects]]
  from = "https://blog.jesusvelez.xyz/Blog/*"
  to = "/Blog/:splat"
  status = 200

[[redirects]]
  from = "https://blog.jesusvelez.xyz/DevBlog"
  to = "/DevBlog"
  status = 200


[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
